SELECT * FROM customer LIMIT 20

--Q1)What is the total revenue generated by male vs female customers ?
SELECT "gender" , SUM("purchase_amount") AS revenue
FROM customer
GROUP BY "gender";

--Q2)Which customers used a discount but still spent more than the average purchase amount ?
SELECT "customer_id", "purchase_amount"
FROM customer
WHERE "discount_applied" = 'Yes'
  AND "purchase_amount" >= (
      SELECT AVG("purchase_amount")
      FROM customer
  );

--Q3)Which are the top 5 products with the highest review rating ?
SELECT "item_purchased", AVG("review_rating") AS "average product rating"
FROM customer
GROUP BY "item_purchased"
ORDER BY AVG("review_rating") DESC
LIMIT 5;

--Q4)Compare the average purchase amounts between standard and express shipping.
SELECT "shipping_type" , 
AVG("purchase_amount")
FROM customer
WHERE "shipping_type" IN ('Standard','Express')
GROUP BY  "shipping_type"

--Q5)Subscription Status"Do subscribed customers spend more ? compare average spend and total revenue between subscribers and non-subscribers.
SELECT "subscription_status",
COUNT("customer_id") AS "Total Customers",
AVG("purchase_amount") AS "avg spend",
SUM("purchase_amount") AS "total revenue"
FROM customer
GROUP BY "subscription_status"
ORDER BY "avg spend", "total revenue" DESC

--Q6)Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
SELECT "subscription_status",
COUNT("customer_id") AS "repeat buyers"
FROM customer
WHERE "previous_purchases" > 5
GROUP BY "subscription_status"

--Q7)What is the revenue contribution of each age group ?
SELECT "age_group",
SUM("purchase_amount") AS "total revenue"
FROM customer
GROUP BY "age_group"
ORDER BY "total revenue" DESC


